export const FETCH_SMARTISTS_USER_BEGIN = 'FETCH_SMARTISTS_USER_BEGIN';
export const FETCH_SMARTISTS_USER_SUCCESS = 'FETCH_SMARTISTS_USER_SUCCESS';
export const FETCH_SMARTISTS_USER_FAILURE = 'FETCH_SMARTISTS_USER_FAILURE';
export const CLEAR_SMARTISTS_USER = 'CLEAR_SMARTISTS_USER';