export const FETCH_SMARTISTS_MEMBER_BEGIN = 'FETCH_SMARTISTS_MEMBER_BEGIN';
export const FETCH_SMARTISTS_MEMBER_SUCCESS = 'FETCH_SMARTISTS_MEMBER_SUCCESS';
export const FETCH_SMARTISTS_MEMBER_FAILURE = 'FETCH_SMARTISTS_MEMBER_FAILURE';
export const CLEAR_SMARTISTS_MEMBER = 'CLEAR_SMARTISTS_MEMBER';

export const FETCH_SMARTISTS_MEMBERS_BEGIN = 'FETCH_SMARTISTS_MEMBERS_BEGIN';
export const FETCH_SMARTISTS_MEMBERS_SUCCESS = 'FETCH_SMARTISTS_MEMBERS_SUCCESS';
export const FETCH_SMARTISTS_MEMBERS_FAILURE = 'FETCH_SMARTISTS_MEMBERS_FAILURE';
export const CLEAR_SMARTISTS_MEMBERS = 'CLEAR_SMARTISTS_MEMBERS';

export const FETCH_FEATURED_ARTWORK_BEGIN = 'FETCH_FEATURED_ARTWORK_BEGIN';
export const FETCH_FEATURED_ARTWORK_SUCCESS = 'FETCH_FEATURED_ARTWORK_SUCCESS';
export const FETCH_FEATURED_ARTWORK_FAILURE = 'FETCH_FEATURED_ARTWORK_FAILURE';
export const CLEAR_FEATURED_ARTWORK = 'CLEAR_FEATURED_ARTWORK';

export const FETCH_PROJECT_BEGIN = 'FETCH_PROJECT_BEGIN';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const FETCH_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE';
export const CLEAR_PROJECT = 'CLEAR_PROJECT';