export const FETCH_SMARTISTS_MEMBER_BEGIN = 'FETCH_SMARTISTS_MEMBER_BEGIN';
export const FETCH_SMARTISTS_MEMBER_SUCCESS = 'FETCH_SMARTISTS_MEMBER_SUCCESS';
export const FETCH_SMARTISTS_MEMBER_FAILURE = 'FETCH_SMARTISTS_MEMBER_FAILURE';
export const CLEAR_SMARTISTS_MEMBER = 'CLEAR_SMARTISTS_MEMBER';

export const FETCH_PORTFOLIO_BEGIN = 'FETCH_PORTFOLIO_BEGIN';
export const FETCH_PORTFOLIO_SUCCESS = 'FETCH_PORTFOLIO_SUCCESS';
export const FETCH_PORTFOLIO_FAILURE = 'FETCH_PORTFOLIO_FAILURE';
export const CLEAR_PORTFOLIO = 'CLEAR_PORTFOLIO';

export const FETCH_PROJECT_BEGIN = 'FETCH_PROJECT_BEGIN';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const FETCH_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE';
export const CLEAR_PROJECT = 'CLEAR_PROJECT';